---
# tasks file for roles/node-exporter

- name: Pull Node-exporter image from Dockerhub
  docker_image:
    name: prom/node-exporter:{{ version }}
    source: pull

- name: Run Node-exporter container
  docker_container:
    name: Node-exporter
    image: prom/node-exporter:{{ version }}
    restart_policy: unless-stopped
    ports:
    - "9100:9100" 