---
- name: Install package for all
  hosts: all
  become: yes
  roles:
  - common
  
- name: Install package for nodes
  hosts: nodes
  become: yes
  roles:
  - docker
  - node-exporter
  

- name: Install package for monitor
  hosts: monitor
  become: yes
  roles:
  #- prometheus
  #- grafana
  - build-push-image
  - monitoring

- name: Deploy webapp on worker1
  hosts: ec2-18-138-227-65.ap-southeast-1.compute.amazonaws.com
  become: yes
  roles:
  - deploy-webapp




      
    
