---
- name: Install package for all
  hosts: all
  become: yes
  roles:
  - common
  - docker
  
- name: Install package for nodes
  hosts: nodes
  become: yes
  roles:
  - node-exporter
  

- name: Install package for monitor
  hosts: monitor
  become: yes
  roles:
  #- prometheus
  #- grafana
  - build-push-image
  - monitoring

- name: Deploy webapp on worker1
  hosts: worker1
  become: yes
  roles:
  - deploy-webapp




      
    
