version: '3.1'

services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: boybanhbeo09
      MYSQL_DATABASE: students
    volumes:
      - ./src/main/resources/db.sql:/docker-entrypoint-initdb.d/db.sql 
    networks:
      - springboot-mysql-net

  
  webapp:
    image: longnh09/springbootapp:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net: