FROM amazoncorretto:17-alpine-jdk
MAINTAINER longnh
COPY student-management-0.0.1-SNAPSHOT.jar student-management-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/student-management-0.0.1-SNAPSHOT.jar"]