FROM python:3.9

LABEL maintainer="longnh"

WORKDIR /usr/src/app/

COPY . .

RUN pip install --upgrade pip && \
	pip install -r requirements.txt
	
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
