---
- name: Install package for all
  hosts: all
  become: yes
  roles:
  - common
  
- name: Install package for nodes
  hosts: nodes
  become: yes
  roles:
  - docker
  - node-exporter
  

- name: Install package for monitor
  hosts: monitor
  become: yes
  roles:
  - prometheus
  - grafana




      
    
