global:
  scrape_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: 
    - localhost:9090
    
- job_name: node
  static_configs:
  - targets: 
    - ec2-13-212-124-39.ap-southeast-1.compute.amazonaws.com:9100
    - ec2-18-143-197-219.ap-southeast-1.compute.amazonaws.com:9100
