---
# tasks file for roles/prometheus
- name: Install Prometheus
  docker_image:
    name: prom/prometheus:latest
    source: pull

- name: Copy prometheus.yml file to /tmp
  copy:
    src: ../files/prometheus.yml
    dest: /tmp

- name: Run Prometheus Docker image
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    restart_policy: unless-stopped
    volumes: /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"